import { HashDataKey, HashRegistryEntry } from "./crypto";

describe("HashRegistryValue", () => {
  it("should match siad for equal input", () => {
    // "h" is the hash generated by siad with the same input parameters
    const h = "0829da934f2fb01232a59e1e9bb44396c343cab0e6328373f121a7e5d8ae1870";
    const hash = HashRegistryEntry({
      datakey: "somedatakey",
      data: "abc",
      revision: 123456789,
    });
    expect(Buffer.from(hash).toString("hex")).toEqual(h);
  });
});
